patricksanto/mentormeet

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20230301190943_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

Adding. Devise in the application

devise added in the app

---

app/controllers/bookings_controller.rb
app/controllers/mentorships_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/models/booking.rb
app/models/mentorship.rb
app/models/review.rb
config/routes.rb
db/migrate/20230301195041_create_mentorships.rb
db/migrate/20230301195217_create_bookings.rb
db/migrate/20230301195246_create_reviews.rb
db/schema.rb
test/controllers/bookings_controller_test.rb
test/controllers/mentorships_controller_test.rb
test/controllers/reviews_controller_test.rb
test/controllers/users_controller_test.rb
test/models/booking_test.rb
test/models/mentorship_test.rb
test/models/review_test.rb

adicionei os models, os controllers e alguns routes

models, controllers e routes added

---

app/models/booking.rb

validating booking

---

app/controllers/mentorships_controller.rb
app/models/mentorship.rb
app/views/mentorships/edit.html.erb
app/views/mentorships/index.html.erb
app/views/mentorships/new.html.erb
app/views/mentorships/show.html.erb
config/routes.rb
db/migrate/20230301195041_create_mentorships.rb

"mentorship validates done, added default false in mentorship migrate file booleans, added actions in mentorship controllers, created mentorships views and changed root route to mentorship index"

Validating mentorship model

---

app/models/user.rb

User validations

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/mentorship_policy.rb
app/policies/review_policy.rb
test/policies/booking_policy_test.rb
test/policies/mentorship_policy_test.rb
test/policies/review_policy_test.rb

using pundit to create authorization process in the app

implement the pundit policies in the app

---

app/controllers/users_controller.rb

a new controller to the view model

user controller and views were generated by devise

---

Gemfile
Gemfile.lock
db/seeds.rb

creating the seed file to Users and Mentorships.
REMEMBER: all users passwords is '123456'

creating the seeds

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/users/show.html.erb
config/routes.rb
test/policies/user_policy_test.rb

created the show page, already authorized for the user model . 
the policy file for users added also,
only allowed to show still.

show pages for users ( including mentors )

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/layouts/application.html.erb
app/views/mentorships/index.html.erb
db/schema.rb

fiz um começo de homepage com o index dos mentorships, e mudei a cor de fundo do site para azul no bootstrap no layout application

index das mentorships aparecendo na root

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/views/mentorships/index.html.erb

_card.scss file created in the componets path. 
card implemented in the index page

Creating card component

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

criei a navbar com mentorship, logo provisoria

created navbar with offer you mentorship and logo

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20230302191721_create_active_storage_tables.active_storage.rb
db/schema.rb

creating the wloudinary setup to attach photo to user

Implementing user photo

---

config/environments/production.rb

cloudinario added in the production enviroment

---

app/models/review.rb
app/models/user.rb

fixing some mistakes in the association , linking tables ( user and booking )

fixing some mistakes in the associasions

---

app/models/booking.rb
app/models/review.rb

changing some things in the validations

a few changes in the validations , reviw model, rating

---

app/models/review.rb

fixing some typos

---

app/assets/stylesheets/application.scss
app/controllers/bookings_controller.rb
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/index.js
app/policies/booking_policy.rb
app/policies/mentorship_policy.rb
app/views/bookings/new.html.erb
app/views/shared/_navbar.html.erb
db/schema.rb
package.json
yarn.lock

adicionei link ao botao icon e falta a hora do booking

Adding new booking

---

app/controllers/mentorships_controller.rb
app/views/mentorships/edit.html.erb
app/views/mentorships/show.html.erb

<%= link_to 'Edit', edit_mentorship_path(@mentorship) %>

Adicionando edit

---

app/views/mentorships/edit.html.erb

<%= link_to 'Edit', edit_mentorship_path(@mentorship) %>

fixing_edit_mentorship

---

app/views/mentorships/show.html.erb
app/views/users/show.html.erb

style page to profile page , title and description to do , nothing is 100% done yet

style in profile page with some changes to do

---

app/views/mentorships/show.html.erb
db/schema.rb

Profile page

---

app/controllers/mentorships_controller.rb
app/views/mentorships/index.html.erb

Adicionando foto da mentorship no index

adding_mentorship_picture

---

app/views/shared/_navbar.html.erb
db/schema.rb

insert user photo in the nav bar ;
fix the grid layout;
fix the link in the "offer a new mentorship"

changes in the navbar

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/devise/registrations/edit.html.erb
app/views/layouts/application.html.erb
app/views/shared/_edit_profile.html.erb
app/views/shared/_navbar.html.erb
app/views/users/dashboard.html.erb
config/routes.rb

dashboard created and the Edit page to the user

dashboard created

---

app/controllers/bookings_controller.rb
app/controllers/mentorships_controller.rb
app/controllers/reviews_controller.rb
app/views/mentorships/show.html.erb
app/views/reviews/new.html.erb
config/routes.rb

Tentando implementar as reviews do user

Reviews back end

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/views/users/dashboard.html.erb

implement the Schedule in the user dashboard

show the schedule in the dashboard

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/users/dashboard.html.erb
db/migrate/20230304211423_add_default_value_to_is_accepted.rb
db/migrate/20230306153500_add_status_to_bookings.rb
db/schema.rb

implement the schedule in the dashboard

Dashboard edit

---

app/controllers/mentorships_controller.rb
app/views/mentorships/show.html.erb

Adicionei booking ao mentorship

---

app/controllers/bookings_controller.rb
app/controllers/mentorships_controller.rb
app/models/booking.rb

Accept mentorships

---

app/javascript/controllers/flatpickr_controller.js
db/schema.rb

botei hora no calendario de schedule

---

app/controllers/reviews_controller.rb
app/views/mentorships/show.html.erb
app/views/users/dashboard.html.erb

Botao para criar review aparece no card da mentorship

added review button

---

app/controllers/bookings_controller.rb
app/models/mentorship.rb
app/policies/booking_policy.rb
app/views/users/dashboard.html.erb
db/schema.rb

include acceptance of mentorship

Mentorship acceptance

---

app/assets/stylesheets/components/_card.scss
app/views/users/dashboard.html.erb

dashboard card finished

---

app/views/mentorships/show.html.erb

agora a foto do mentorship leva pro perfil de quem fez a mentoria

fixing photo in mentorship, now redirect to the user owner

---

app/views/mentorships/show.html.erb
app/views/users/dashboard.html.erb

the review card was added to the mentorship show pages

added a review box in the mentorships show page

---

app/models/mentorship.rb
app/views/mentorships/edit.html.erb
app/views/mentorships/show.html.erb

fix some bugs while the user trying to edit or delete their mentorships

fix some bugs in edit and delete

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/config/_fonts.scss
app/views/mentorships/index.html.erb
app/views/shared/_banner.html.erb

style for bvanner

---

app/views/mentorships/index.html.erb

fix some mistakes
